global_defs {
    router_id WEB1
}

vrrp_script check_nginx {
    script "/usr/bin/systemctl is-active --quiet nginx"
    interval 2
    fall 2
    rise 2
}

vrrp_instance VI_1 {
    state MASTER
    interface enp0s8

    virtual_router_id 51
    priority 110
    advert_int 1

    unicast_src_ip 192.168.56.11
    unicast_peer {
        192.168.56.12
    }

    virtual_ipaddress {
        192.168.56.20/24 dev enp0s8
    }

    track_script {
        check_nginx
    }
}