server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name test.com www.test.com;

    root /var/www/lab;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}